service: ld 

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  profile: apofc
  region: us-east-1
# stage: dev

# iamRoleStatements:
#     - Effect: Allow
#       Action:
#         - sqs:*
#       Resource: "*"
#     - Effect: "Allow"
#       Action:
#         - "s3:*"
#       Resource: "*"   
# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
environment:
  sqsUrl: "queueUrl"

functions:
  process:
    handler: handler.process
