service: emailProcessor

provider:
    name: aws
    runtime: nodejs6.10
    profile: apofc
    region: us-east-1
    memorySize: 128
    timeout: 6
    environment:
        sqsUrl: 'sqsQueueUrl'
        s3Url: 's3BucketUrl'
    iamRoleStatements:
        - Effect: Allow
          Action:
              - sqs:*
          Resource: 'arn:aws:sqs:us-east-1:338805238106:*'
        - Effect: 'Allow'
          Action:
              - 's3:*'
          Resource: '*'

functions:
    process:
        handler: handler.process
        description: process emails from sqs and put html in s3
        events:
            - http: get process
            - schedule:
                  name: task-US
                  description: Email processor task for US
                  rate: rate(5 minutes)
                  enabled: false
                  input:
                      countryCode: US
            - schedule:
                  name: task-GB
                  description: Email processor task for GB
                  rate: rate(5 minutes)
                  enabled: false
                  input:
                      countryCode: GB

resources:
    ? Resources

# plugins:
#     - serverless-offline
