service: emailProcessor

provider:
    name: aws
    runtime: nodejs6.10
    profile: apofc
    region: ${opt:region, 'us-east-1'}
    memorySize: 128
    timeout: 6
    environment:
        sqsUrl: ${s3:saltConfig/sqsUrl}
        s3Url: ${s3:saltConfig/s3Url}
        numOfMsgToReadFromSQS: ${env:numOfMsg}
    iamRoleStatements:
        - Effect: Allow
          Action:
              - sqs:*
          Resource: 'arn:aws:sqs:us-east-1:338805238106:*'
        - Effect: 'Allow'
          Action:
              - 's3:*'
          Resource: '*'

custom:
    globalSchedule: rate(5 minutes)
    schedulerEnabled: false

functions:
    process:
        handler: handler.process
        description: process emails from sqs and put html in s3
        events:
            - http: get process
            - schedule:
                  name: task-US
                  description: Email processor task for US
                  rate: ${self:custom.globalSchedule}
                  enabled: ${self:custom.schedulerEnabled}
                  input:
                      countryCode: US
            - schedule:
                  name: task-GB
                  description: Email processor task for GB
                  rate: ${self:custom.globalSchedule}
                  enabled: ${self:custom.schedulerEnabled}
                  input:
                      countryCode: GB

resources:
    ? Resources: ${file(cloudformation-resources.json)}

# plugins:
#     - serverless-offline
